import os
import uuid
import hashlib
from datetime import datetime, timezone
import logging
from app.qdrant_store import upsert_chunk_vector, search_vectors
from app.embeddings import get_embedding
from app.config import settings

logger = logging.getLogger(__name__)

TRUST_SCORES = {
    "Project Memory": 100,
    "User Decisions": 100,
    "Official Documentation": 95,
    "Verified Fixes": 95,
    "Verified Examples": 90,
    "Architecture Patterns": 85,
    "Testing Patterns": 85,
    "Infrastructure Knowledge": 85,
    "Implementation Decisions": 80,
    "Learning Resources": 60,
    "General Reference Material": 50
}

def get_trust(topic: str) -> int:
    return TRUST_SCORES.get(topic, 50)

def _deduplicate_and_insert(project_id: str, topic: str, text: str, now: str, source_type: str, version: str = "latest", usage_type: str = "execution", status: str = "stable"):
    """
    Checks if identical text exists. If yes, skip.
    If different text exists for the same topic/context, insert new and mark old as superseded.
    """
    content_hash = hashlib.sha256(text.encode("utf-8")).hexdigest()
    vector = get_embedding(text)
    
    try:
        from qdrant_client.http.models import Filter, FieldCondition, MatchValue
        from app.qdrant_store import get_client
        client = get_client()
        
        # Check identical content hash
        match = client.scroll(
            collection_name=settings.QDRANT_COLLECTION,
            scroll_filter=Filter(
                must=[
                    FieldCondition(key="content_hash", match=MatchValue(value=content_hash)),
                    FieldCondition(key="project", match=MatchValue(value=project_id))
                ]
            ),
            limit=1
        )[0]
        
        if match:
            # Duplicate found, skip
            return
            
    except Exception as e:
        logger.error(f"Error checking duplicates in Qdrant: {e}")
        
    meta = {
        "source": source_type,
        "trust_level": get_trust(topic),
        "version": version,
        "project": project_id,
        "topic": topic,
        "timestamp": now,
        "usage_type": usage_type,
        "status": status,
        "content_hash": content_hash,
        "superseded": False
    }
    
    upsert_chunk_vector(str(uuid.uuid4()), vector, meta, text)


def update_markdown_log(project_id: str, updated_markdown: str):
    """
    Maintains the structured local markdown file.
    Overwrites the old file with the intelligently merged file generated by the LLM.
    """
    if not updated_markdown:
        return
        
    memory_log_path = os.path.join(settings.UPLOAD_DIR, f"project_{project_id}_memory.md")
    with open(memory_log_path, "w", encoding="utf-8") as f:
        f.write(updated_markdown)


async def ingest_memory(project_id: str, memory_data: dict):
    now = datetime.now(timezone.utc).isoformat()
    
    # 1. Project Memory
    for text in memory_data.get("project_memory_updates", []):
        _deduplicate_and_insert(project_id, "Project Memory", text, now, "project_memory")
        
    # 2. User Decisions
    for text in memory_data.get("user_decisions", []):
        _deduplicate_and_insert(project_id, "User Decisions", text, now, "user_decision")
        
    # 3. Architecture Decisions
    for arch in memory_data.get("architecture_decisions", []):
        text = f"Architecture Decision: {arch.get('decision', '')}\nReasoning: {arch.get('reasoning', '')}"
        _deduplicate_and_insert(project_id, "Architecture Patterns", text, now, "architecture_patterns")
        
    # 4. Implementation Decisions
    for imp in memory_data.get("implementation_decisions", []):
        text = f"Implementation Decision: {imp.get('decision', '')}\nJustification: {imp.get('justification', '')}"
        _deduplicate_and_insert(project_id, "Implementation Decisions", text, now, "implementation_decisions")
        
    # 5. Verified Fixes
    for fix in memory_data.get("verified_fixes", []):
        text = (
            f"VERIFIED FIX\n"
            f"Problem: {fix.get('problem', '')}\n"
            f"Root Cause: {fix.get('root_cause', '')}\n"
            f"Fix Applied: {fix.get('fix_applied', '')}\n"
            f"Files Changed: {fix.get('files_changed', '')}\n"
            f"Verification Method: {fix.get('verification_method', '')}\n"
            f"Final Result: {fix.get('final_result', '')}"
        )
        _deduplicate_and_insert(project_id, "Verified Fixes", text, now, "verified_fixes")
        
    # 6. Verified Examples
    for text in memory_data.get("verified_code_examples", []):
        _deduplicate_and_insert(project_id, "Verified Examples", text, now, "verified_examples")
        
    # 7. Testing Patterns
    for text in memory_data.get("testing_patterns", []):
        _deduplicate_and_insert(project_id, "Testing Patterns", text, now, "testing_patterns")
        
    # 8. Infrastructure Knowledge
    for text in memory_data.get("infrastructure_knowledge", []):
        _deduplicate_and_insert(project_id, "Infrastructure Knowledge", text, now, "infrastructure_knowledge")
        
    # 9. Completed Tasks
    for task in memory_data.get("completed_tasks", []):
        text = (
            f"COMPLETED TASK\n"
            f"What was built: {task.get('what_was_built', '')}\n"
            f"Why it was built: {task.get('why_it_was_built', '')}\n"
            f"What changed: {task.get('what_changed', '')}\n"
            f"Tests passed: {task.get('tests_passed', '')}\n"
            f"Issues fixed: {task.get('issues_fixed', '')}\n"
            f"Next steps: {task.get('next_steps', '')}"
        )
        # Store as Project Memory with highest trust
        _deduplicate_and_insert(project_id, "Project Memory", text, now, "completed_tasks")
        
    # Write the full human-readable Markdown log intelligently merged by the LLM
    updated_markdown = memory_data.get("updated_project_memory_markdown", "")
    update_markdown_log(project_id, updated_markdown)
    
    logger.info(f"Memory successfully ingested for project {project_id}")
