import logging
import asyncio
from typing import Dict, Any, List
from pathlib import Path

from app.config import settings

from app.planner import create_plan
from app.coder import draft_code_changes
from app.apply_changes import apply_drafted_changes

logger = logging.getLogger(__name__)

async def run_orchestrator(idea: str, context_files: List[str] = None) -> Dict[str, Any]:
    """
    The master loop that ties Planner -> Coder -> Applier together.
    It takes an idea, breaks it into phases, and recursively executes them.
    """
    logger.info(f"Starting Orchestrator for idea: {idea}")
    if context_files is None:
        context_files = []
        
    execution_log = []
        
    try:
        # Step 0: Save the raw prompt to maintain context
        workspace_dir = Path(settings.WORKSPACE_ROOT)
        workspace_dir.mkdir(parents=True, exist_ok=True)
        
        raw_prompt_path = workspace_dir / "raw_prompt.md"
        with open(raw_prompt_path, "w", encoding="utf-8") as f:
            f.write(f"# Original Request\n\n{idea}\n")
        logger.info(f"Saved raw prompt to {raw_prompt_path}")

        # Step 1: Call Planner to get the phases
        logger.info("Calling Planner...")
        plan_result = await create_plan(idea)
        
        phases = plan_result.get("phases", [])
        if not phases:
             logger.warning("Planner returned no phases.")
             return {"status": "error", "message": "No phases generated by Planner.", "log": execution_log}
             
        logger.info(f"Planner generated {len(phases)} phases. Beginning execution loop.")
        
        # Write the generated plan.md
        plan_path = workspace_dir / "plan.md"
        with open(plan_path, "w", encoding="utf-8") as f:
            f.write(f"# Implementation Plan\n\nGoal: {plan_result.get('goal', '')}\nSummary: {plan_result.get('summary', '')}\n\n")
            for phase in phases:
                f.write(f"## Phase {phase.get('id')}: {phase.get('title')}\n")
                f.write(f"{phase.get('description', '')}\n\n")
        logger.info(f"Saved plan to {plan_path}")
        
        features_path = workspace_dir / "features.md"
        if not features_path.exists():
            with open(features_path, "w", encoding="utf-8") as f:
                f.write("# Built Features Log\n\n")

        # Step 2: Loop over phases
        for idx, phase in enumerate(phases):
            phase_id = phase.get('id', idx+1)
            phase_title = phase.get('title', f"Phase {phase_id}")
            logger.info(f"--- Executing {phase_title} ---")
            
            # Formulate the Coder prompt based on the phase goal
            coder_task = f"Executing project phase: {phase_title}. Description: {phase.get('description', '')}. Overall Project Idea: {idea}"
            coder_context_files = phase.get("files_likely_needed", context_files)
            
            # Step 2a: Draft the code
            logger.info("Calling Coder to draft changes...")
            coder_result = await draft_code_changes(task=coder_task, file_paths=coder_context_files)
            proposed_changes = coder_result.get("proposed_changes", [])
            
            phase_log = {
                "phase_id": phase_id,
                "title": phase_title,
                "drafted_changes_count": len(proposed_changes)
            }
            
            if not proposed_changes:
                logger.info(f"No file changes drafted for {phase_title}.")
                phase_log["status"] = "skipped_no_changes"
                execution_log.append(phase_log)
                continue
                
            # Step 2b: Apply the code safely
            logger.info(f"Applying {len(proposed_changes)} drafted changes...")
            apply_results = apply_drafted_changes(proposed_changes)
            
            # Log results
            success_count = sum(1 for r in apply_results if r.get("status") == "success")
            phase_log["status"] = "applied"
            phase_log["success_count"] = success_count
            phase_log["details"] = apply_results
            execution_log.append(phase_log)
            
            logger.info(f"Finished {phase_title}. Successfully applied {success_count}/{len(proposed_changes)} files.")
            
            with open(features_path, "a", encoding="utf-8") as f:
                f.write(f"- [x] **{phase_title}**: Successfully applied {success_count} file changes.\n")
            # Optional: In the future, we could trigger Browser tests here before moving to the next phase!
            # await asyncio.sleep(1) # Small pause between heavy LLM tasks
            
        logger.info("Orchestrator completed all phases successfully!")
        return {
            "status": "success",
            "idea": idea,
            "total_phases": len(phases),
            "log": execution_log
        }

    except Exception as e:
        logger.error(f"Orchestrator failed: {e}")
        return {"status": "error", "message": str(e), "log": execution_log}
